# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e056f2f704d242785804f7602e0d4e6f9198481a4aa3cf2fc8a943dfc8ace6c257bc80625152137414fe8e373c63de4543d91a44002dda282d752592b8ad3c5

test:
  secret_key_base: 8dd97a501349cc01ad6c623db4da200458a22282b4e1d1e4b5ac7bce20a6d2c6a33bc2c8c057ecdcd2a9e606226f9721e18d7648c8b54352f7239b9dc2b0f500

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
